""" This script explores publishing ROS messages in ROS using Python """
import rclpy
import numpy as np
from rclpy.node import Node
from std_msgs.msg import Header
from geometry_msgs.msg import Twist, Vector3, Pose, Quaternion
from nav_msgs.msg import Odometry
from typing import Literal, Optional

def quat_to_yaw(q: Quaternion) -> float:
    """Computes the yaw angle from a quaternion.
    Input: q(Quaternion) -- a quaternion
    Output: yaw(float) -- the yaw angle in radians
    THIS FUNCTION WAS GENERATED BY GITHUB COPILOT
    """
    siny_cosp = 2 * (q.w * q.z + q.x * q.y)
    cosy_cosp = 1 - 2 * (q.y * q.y + q.z * q.z)
    return np.arctan2(siny_cosp, cosy_cosp)

class DriveSquareNode(Node):
    """This node will drive the neato in a hard-coded 1x1m square."""
    def __init__(self):
        """Initializes the DriveSquareNode. No inputs."""
        super().__init__('drive_square_node')
        # Create a timer that fires ten times per second
        timer_period = 0.1
        self.vel_timer = self.create_timer(timer_period, self.compute_and_send_vel)
        self.vel_publisher = self.create_publisher(Twist, 'cmd_vel', 10)
        self.odom_subscriber = self.create_subscription(Odometry, 'odom', self.process_odom, 10)
        self.drive_state: Literal['line'] | Literal['corner'] | Literal['done'] = 'line'
        self.action_started_at: Optional['Pose'] = None
        self.edges_complete = 0

    def compute_and_send_vel(self):
        forward_vel = 0.0
        angular_vel = 0.0
        match self.drive_state:
            case 'line':
                forward_vel = 0.2
            case 'corner':
                angular_vel = 0.5
        twist_msg = Twist(linear=Vector3(x=forward_vel,y=0.0,z=0.0), angular=Vector3(x=0.0,y=0.0,z=angular_vel))
        self.vel_publisher.publish(twist_msg)
        
    def process_odom(self, msg: Odometry):
        """Gets odom data"""
        pose = msg.pose.pose

        if self.action_started_at is None:
            self.action_started_at = pose
        
        match self.drive_state:
            case 'line':
                dist = np.sqrt((pose.position.x-self.action_started_at.position.x)**2 + 
                        (pose.position.y-self.action_started_at.position.y)**2)
                if dist >= 1:
                    self.drive_state = 'corner'
                    self.action_started_at = pose
                    self.compute_and_send_vel()
            case 'corner':
                if abs(quat_to_yaw(pose.orientation) - quat_to_yaw(self.action_started_at.orientation)) > 90*np.pi/180:
                    self.drive_state = 'line'
                    self.action_started_at = pose
                    self.edges_complete += 1
                    self.compute_and_send_vel()

        if self.edges_complete >= 4:
            # square complete
            self.drive_state = 'done'
            # stop moving
            self.compute_and_send_vel()
            # tear down this node
            raise SystemExit

def main(args=None):
    """Initializes a node, runs it, and cleans up after termination.
    Input: args(list) -- list of arguments to pass into rclpy. Default None.
    """
    rclpy.init(args=args)      # Initialize communication with ROS
    node = DriveSquareNode()   # Create our Node
    try:
        rclpy.spin(node)           # Run the Node until ready to shutdown
    finally:
        # print("exiting cleanly") # Testing if this would code would run
        rclpy.shutdown()           # cleanup

if __name__ == '__main__':
    main()
