""" This script explores publishing ROS messages in ROS using Python """
import rclpy
import numpy as np
from rclpy.node import Node
from geometry_msgs.msg import Twist, Vector3, Pose, Quaternion
from nav_msgs.msg import Odometry
from sensor_msgs.msg import PointCloud2
from std_msgs.msg import String
from typing import List, Literal, NamedTuple, Optional, Tuple
from sensor_msgs_py import point_cloud2

def quat_to_yaw(q: Quaternion) -> float:
    """Computes the yaw angle from a quaternion.
    Input: q(Quaternion) -- a quaternion
    Output: yaw(float) -- the yaw angle in radians
    THIS FUNCTION WAS GENERATED BY GITHUB COPILOT
    """
    siny_cosp = 2 * (q.w * q.z + q.x * q.y)
    cosy_cosp = 1 - 2 * (q.y * q.y + q.z * q.z)
    return np.arctan2(siny_cosp, cosy_cosp)

def print_pose(pose: Pose):
    print(pose.position.x, pose.position.y)
    print(quat_to_yaw(pose.orientation)*180/np.pi)
    
def short_way_around_angle(angle, ref_angle):
    diff = quat_to_yaw(angle)-quat_to_yaw(ref_angle)
    if diff > np.pi:
        return diff-2*np.pi
    elif diff < -np.pi:
        return diff+2*np.pi
    else:
        return diff
class SuspiciousNode(Node):
    """This node will handle the suspicous behavior."""
    def __init__(self):
        """Initializes the SuspiciousNode. No inputs."""
        super().__init__('suspicious_node')
        # Create a timer that fires ten times per second
        timer_period = 0.1
        self.main_loop_timer = self.create_timer(timer_period, self.main_loop)
        self.vel_publisher = self.create_publisher(Twist, 'cmd_vel', 10)
        self.state_publisher = self.create_publisher(String, 'current_state', 10)
        self.odom_subscriber = self.create_subscription(Odometry, 'odom', self.process_odom, 10)
        self.state_subscriber = self.create_subscription(String, 'current_state', self.update_state, 10)
        self.detecter_objetcs_subscriber = self.create_subscription(PointCloud2, 'detected_clusters', self.detected_objects, 10)
        
        self.active = False
        self.active_pos: NamedTuple = None
        self.active_pos_start: NamedTuple = None
        
        self.timeOut = 5
        self.kP = 0.2 #TODO: set this value
        
        self.target_turn_amount = None;
        self.turn_start_angle = None;
        self.current_angle = None;
        
        self.mode: Literal['Setup'] | Literal['Turning'] | Literal['Watching'] = 'Setup'


    def update_state(self, msg: String):
        self.active = (msg.data == "suspicious")
        print(f"Node: 'suspicious' -- recived state: {msg.data}, active?: {self.active}")
        
    def detected_objects(self, msg: PointCloud2):
        if (not self.active) or self.mode == 'Turning':
            return
        objects = point_cloud2.read_points_list(msg, ["x", "y"])
        closest = None
        closest_dist = 10000
        for (i, obj) in enumerate(objects):
            if obj.y <= 0:
                if (obj.x**2 + obj.y**2 < closest_dist): closest = i
        if closest is not None:
            self.active_pos = objects[closest]
            if self.mode == 'Setup':
                self.target_turn_amount = np.arctan2(self.active_pos.y, self.active_pos.x)
                self.mode = 'Turning'
            elif self.mode == 'Watching':
                if self.active_pos_start is None:
                    self.active_pos_start = self.active_pos
        else:
            self.active_pos = None
        
        
    def main_loop(self):
        if not self.active or self.mode == 'Setup':
            return
        if self.mode == 'Turning':
            self.compute_and_send_vel()
            if self.check_complete():
                self.send_stop()
                self.mode = 'Watching'
        if self.mode == 'Watching':
            pass
        
        
    def process_odom(self, msg: Odometry):
        if not self.active:
            return
        self.current_angle = quat_to_yaw(msg.pose.pose.orientation)
        if self.turn_start_angle is None:
            self.turn_start_angle = self.current_angle
            
            
    def check_complete(self):
        angle_traveled = short_way_around_angle(self.current_angle, self.turn_start_angle)
        return abs(abs(angle_traveled) - abs(self.target_turn_amount)) < np.deg2rad(5)

    def compute_and_send_vel(self):
        angle_traveled = short_way_around_angle(self.current_angle, self.turn_start_angle)
        error = abs(self.target_turn_amount) - abs(angle_traveled)
        angular_vel = -self.kP*error
        
        twist_msg = Twist(linear=Vector3(x=0.0,y=0.0,z=0.0), angular=Vector3(x=0.0,y=0.0,z=angular_vel))
        self.vel_publisher.publish(twist_msg)
        
    def send_stop(self):
        twist_msg = Twist(linear=Vector3(x=0.0,y=0.0,z=0.0), angular=Vector3(x=0.0,y=0.0,z=0.0))
        self.vel_publisher.publish(twist_msg)


def main(args=None):
    """Initializes a node, runs it, and cleans up after termination.
    Input: args(list) -- list of arguments to pass into rclpy. Default None.
    """
    rclpy.init(args=args)      # Initialize communication with ROS
    node = SuspiciousNode()   # Create our Node
    try:
        rclpy.spin(node)           # Run the Node until ready to shutdown
    finally:
        # print("exiting cleanly") # Testing if this would code would run
        rclpy.shutdown()           # cleanup

if __name__ == '__main__':
    main()
